services:

  ghost:
    # image: ghost-s3:latest
    build: .
    restart: always
    ports:
      - 2368:2368
    environment:
      # # see https://ghost.org/docs/config/#configuration-options
      # database__client: mysql
      # database__connection__host: db
      # database__connection__user: user1
      # database__connection__password: secretPassword
      # database__connection__database: ghost

      url: http://localhost:2368 # Change this

      NODE_ENV: development # default: production

      storage__active: s3
      storage__s3__accessKeyId: accessKey # Change this
      storage__s3__secretAccessKey: accessKeySecret # Change this
      storage__s3__region: AWS-S3-REGION # Change this
      storage__s3__bucket: BucketName # Change this
      storage__s3__assetHost: https://UNIQUE.cloudfront.net # Change this
      storage__s3__pathPrefix: images # Optional, Set this if you want all images to be stored in a subfolder
      storage__s3__forcePathStyle: true
      storage__s3__acl: private
    volumes:
      - ghost:/var/lib/ghost/content

volumes:
  ghost: