name: Publish Docker image

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Prepare Docker tags
        id: prepareTag
        run: |
          if [[ ${{ github.ref }} == 'refs/tags/'* ]]; then
          TAGS="${{ github.repository }}:${{ github.ref_name }},"
          else
            TAGS=""
          fi
          TAGS+="${{ github.repository }}:latest"
          echo "{tags}={$TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push with latest tag
        uses: docker/build-push-action@v5
        with:
          context: "."
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: ${{ steps.prepareTag.outputs.tags }}